apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: image-classifier

resources:
- prometheus-rbac.yaml
- prometheus-configmap.yaml
- prometheus-pvc.yaml
- prometheus-deployment.yaml
- prometheus-service.yaml
- node-exporter-daemonset.yaml
- grafana-pvc.yaml
- grafana-deployment.yaml
- grafana-service.yaml

labels:
- pairs:
    app: monitoring-stack
    version: v1
