apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      # - "first_rules.yml"
      # - "second_rules.yml"

    scrape_configs:
      # Prometheus itself
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # Image Classifier Service
      - job_name: 'image-classifier'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - image-classifier
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: image-classifier-service
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: http
        metrics_path: '/metrics'
        scrape_interval: 10s
        scrape_timeout: 5s

      # Node Exporter
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - monitoring
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: node-exporter
        scrape_interval: 15s

      # cAdvisor
      - job_name: 'cadvisor'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - monitoring
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: cadvisor
        scrape_interval: 15s
