apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: image-classifier

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
- ingress.yaml
- network-policy.yaml

commonLabels:
  app: scalable-image-classifier
  version: v1

images:
- name: scalable-image-classifier
  newTag: latest
