apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: image-classifier
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /var/log/app/*.log
        - /app/logs/*.log
      fields:
        service: image-classifier
      fields_under_root: true
      multiline.pattern: '^\d{4}-\d{2}-\d{2}'
      multiline.negate: true
      multiline.match: after
    
    - type: container
      enabled: true
      paths:
        - /var/lib/docker/containers/*/*.log
      fields:
        service: kubernetes
      fields_under_root: true
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/lib/docker/containers/"
    
    output.logstash:
      hosts: ["logstash:5044"]
    
    logging.level: info
    logging.to_files: true
    logging.files:
      path: /var/log/filebeat
      name: filebeat
      keepfiles: 7
      permissions: 0644
