apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: image-classifier
  labels:
    app: logstash
spec:
  type: ClusterIP
  ports:
  - port: 5044
    targetPort: 5044
    name: beats
  selector:
    app: logstash
