apiVersion: batch/v1
kind: Job
metadata:
  name: copy-model-job
  namespace: kserve-comparison
spec:
  template:
    spec:
      containers:
      - name: copy-model
        image: busybox
        command: ["/bin/sh"]
        args:
        - -c
        - |
          echo "Copying model files..."
          cp -r /source/* /mnt/models/
          ls -la /mnt/models/
          echo "Model files copied successfully"
        volumeMounts:
        - name: source-volume
          mountPath: /source
        - name: model-volume
          mountPath: /mnt/models
      volumes:
      - name: source-volume
        hostPath:
          path: /c/Users/anast/Documents/Repos/athtech-scalable-image-classifier/comparisons/kserve/model-store
          type: Directory
      - name: model-volume
        persistentVolumeClaim:
          claimName: mobilenet-model-pvc
      restartPolicy: Never
  backoffLimit: 3
