apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobilenet-model-pvc
  namespace: kserve-comparison
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath

