apiVersion: v1
kind: Service
metadata:
  name: tensorflow-serving-proxy-service
  namespace: tfserving-simple
  labels:
    app: tensorflow-serving-proxy
spec:
  type: ClusterIP
  ports:
  - port: 8500
    targetPort: 8500
    protocol: TCP
    name: grpc
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http-proxy
  selector:
    app: tensorflow-serving-proxy

